### ISSUE TITLE
jsとcssを見直す

### ISSUE THREAD

**Issue by good1luck21** [aokishun/npo_html#1]
# ファイルが多すぎて何が何なのかわからない。
- [x] css内のファイルの整理
- [x] js内のファイルの整理

--------------------
# ファイル名から昨日が推察できない。
- [ ] css内のファイルの命名を見直してみて
- [ ] js内のファイルの命名を見直してみて

**Comment by good1luck21** [comment]
#1 コミットする時にイシュー番号付けてコミットすると紐付いて便利だよ

**Comment by aokishun** [comment]
次コミットするとき、気をつけます！

**Comment by aokishun** [comment]
#1ああああ

**Comment by aokishun** [comment]
#1 ああああ
